// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto";

export class CompiledInstruction {
  static encode(message: CompiledInstruction, writer: Writer): void {
    writer.uint32(8);
    writer.uint32(message.programIdIndex);

    writer.uint32(18);
    writer.bytes(message.accounts);

    writer.uint32(26);
    writer.bytes(message.data);
  }

  static decode(reader: Reader, length: i32): CompiledInstruction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CompiledInstruction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.programIdIndex = reader.uint32();
          break;

        case 2:
          message.accounts = reader.bytes();
          break;

        case 3:
          message.data = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  programIdIndex: u32;
  accounts: Uint8Array;
  data: Uint8Array;

  constructor(
    programIdIndex: u32 = 0,
    accounts: Uint8Array = new Uint8Array(0),
    data: Uint8Array = new Uint8Array(0)
  ) {
    this.programIdIndex = programIdIndex;
    this.accounts = accounts;
    this.data = data;
  }
}
