// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto";

export class MessageAddressTableLookup {
  static encode(message: MessageAddressTableLookup, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.accountKey);

    writer.uint32(18);
    writer.bytes(message.writableIndexes);

    writer.uint32(26);
    writer.bytes(message.readonlyIndexes);
  }

  static decode(reader: Reader, length: i32): MessageAddressTableLookup {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MessageAddressTableLookup();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.accountKey = reader.bytes();
          break;

        case 2:
          message.writableIndexes = reader.bytes();
          break;

        case 3:
          message.readonlyIndexes = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  accountKey: Uint8Array;
  writableIndexes: Uint8Array;
  readonlyIndexes: Uint8Array;

  constructor(
    accountKey: Uint8Array = new Uint8Array(0),
    writableIndexes: Uint8Array = new Uint8Array(0),
    readonlyIndexes: Uint8Array = new Uint8Array(0)
  ) {
    this.accountKey = accountKey;
    this.writableIndexes = writableIndexes;
    this.readonlyIndexes = readonlyIndexes;
  }
}
