// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto";
import { Message } from "./Message";

export class Transaction {
  static encode(message: Transaction, writer: Writer): void {
    const signatures = message.signatures;
    if (signatures.length !== 0) {
      for (let i: i32 = 0; i < signatures.length; ++i) {
        writer.uint32(10);
        writer.bytes(signatures[i]);
      }
    }

    const message_2 = message.message;
    if (message_2 !== null) {
      writer.uint32(18);
      writer.fork();
      Message.encode(message_2, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Transaction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Transaction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.signatures.push(reader.bytes());
          break;

        case 2:
          message.message = Message.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  signatures: Array<Uint8Array>;
  message: Message | null;

  constructor(
    signatures: Array<Uint8Array> = [],
    message: Message | null = null
  ) {
    this.signatures = signatures;
    this.message = message;
  }
}
