// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto";

export class TransactionError {
  static encode(message: TransactionError, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.err);
  }

  static decode(reader: Reader, length: i32): TransactionError {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TransactionError();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.err = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  err: Uint8Array;

  constructor(err: Uint8Array = new Uint8Array(0)) {
    this.err = err;
  }
}
